FROM ros:humble
ARG USERNAME=paks
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Delete user if it exists in container (e.g Ubuntu Noble: ubuntu)
RUN if id -u $USER_UID ; then userdel `id -un $USER_UID` ; fi

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt update \
    && apt install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
RUN apt update && apt upgrade -y
RUN apt install -y python3-pip
ENV SHELL /bin/bash

RUN apt update && apt install -y ros-humble-joint-state-publisher ros-humble-joint-state-publisher-gui \
    ros-humble-xacro ros-humble-ros-core ros-humble-urdf 

# Install prerequisites and setup Gazebo Sim and ROS 2 bridge
RUN apt update && apt install -y \
    wget \
    gnupg2 \
    lsb-release 
# Add Gazebo Sim repository

RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg\
    && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable jammy main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null

RUN sudo apt update && \
    sudo apt install -y gz-harmonic ros-humble-ros-gzharmonic libgz-transport14-dev ros-humble-foxglove-bridge ros-humble-rosbag2-storage-mcap


# Set up Gazebo environment variables
# ENV GAZEBO_MODEL_PATH=/usr/share/gz/models
# ENV GZ_SIM_RESOURCE_PATH=/usr/share/gz

ENV GNU_HOST=aarch64-linux-gnu
ENV C_COMPILER_ARM_LINUX=$GNU_HOST-gcc
ENV CXX_COMPILER_ARM_LINUX=$GNU_HOST-g++

ENV CROSS_INSTALL_PREFIX=/usr/$GNU_HOST
ENV CROSS_TOOLCHAIN=/arm.toolchain.cmake

# https://cmake.org/cmake/help/v3.16/manual/cmake-toolchains.7.html#cross-compiling-for-linux
# https://cmake.org/cmake/help/v2.8.11/cmake.html#variable%3aCMAKE_PREFIX_PATH
WORKDIR /cross-tools
RUN echo "set(CMAKE_SYSTEM_NAME Linux)" >> arm.toolchain.cmake && \
    echo "set(CMAKE_SYSTEM_PROCESSOR arm)" >> arm.toolchain.cmake && \
    echo "set(CMAKE_C_COMPILER /usr/bin/$C_COMPILER_ARM_LINUX)" >> arm.toolchain.cmake && \
    echo "set(CMAKE_CXX_COMPILER /usr/bin/$CXX_COMPILER_ARM_LINUX)" >> arm.toolchain.cmake && \
    echo "set(CMAKE_PREFIX_PATH $CROSS_INSTALL_PREFIX)" >> arm.toolchain.cmake


RUN sudo apt-get update && \
    sudo apt-get --no-install-recommends install -y autoconf \
    automake \
    build-essential \
    ca-certificates \
    curl \
    # C/C++ cross compilers
    gcc-$GNU_HOST \
    g++-$GNU_HOST \
    git \
    gnupg \
    libssl-dev \
    openssh-client \
    pkg-config \
    software-properties-common \
    wget && \
    sudo rm -rf /var/lib/apt/lists/*

ENV CMAKE_VERSION 3.16.4

RUN export CMAKE_DIR=cmake-$CMAKE_VERSION && \
    export CMAKE_ARCH=$CMAKE_DIR.tar.gz && \
    wget --progress=bar:force:noscroll https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/$CMAKE_ARCH && \
    tar -xzf $CMAKE_ARCH && \
    cd $CMAKE_DIR && \
    ./bootstrap --parallel=`nproc` && \
    make -j `nproc` && \
    sudo make install && \
    rm -rf ../$CMAKE_ARCH \
    ../$CMAKE_DIR

ENV RPI_SHA=f73fca0
ENV WIRINGPI_SHA=6d9ce35

# Set working directory to a writable location
WORKDIR /workspace

# MMAL/VCOS (https://github.com/raspberrypi/userland)
RUN RPI_DIR=/workspace/raspberrypi && \
    RPI_BUILD_DIR=$RPI_DIR/build/arm-linux/release && \
    git clone --single-branch --branch master https://github.com/raspberrypi/userland.git $RPI_DIR && \
    cd $RPI_DIR && \
    git checkout $RPI_SHA && \
    mkdir -p $RPI_BUILD_DIR && \
    cd $RPI_BUILD_DIR && \
    cmake -DCMAKE_TOOLCHAIN_FILE=../../../makefiles/cmake/toolchains/arm-linux-gnueabihf.cmake \
    -DCMAKE_BUILD_TYPE=Release \
    ../../.. && \
    make -j $(nproc) && \
    sudo mkdir -p $CROSS_INSTALL_PREFIX/usr/arm-linux-gnueabihf/opt/vc/src/hello_pi && \  
    sudo make install DESTDIR=$CROSS_INSTALL_PREFIX/ && \
    cd /workspace && \
    rm -rf $RPI_DIR 

RUN PIGPIO_DIR=/workspace/pigpio && \
    git clone --single-branch --branch master https://github.com/joan2937/pigpio.git $PIGPIO_DIR && \
    cd $PIGPIO_DIR && \
    make CROSS_COMPILE=$GNU_HOST- CC=$GNU_HOST-gcc CXX=$GNU_HOST-g++ AR=$GNU_HOST-ar LD=$GNU_HOST-ld STRIP=$GNU_HOST-strip -j$(nproc) && \
    sudo make CROSS_COMPILE=$GNU_HOST- CC=$GNU_HOST-gcc CXX=$GNU_HOST-g++ AR=$GNU_HOST-ar LD=$GNU_HOST-ld STRIP=$GNU_HOST-strip install DESTDIR=$CROSS_INSTALL_PREFIX PREFIX="" && \
    cd /workspace && \
    rm -rf $PIGPIO_DIR



# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME
CMD ["/bin/bash"]