spiral_zipper:
  servo_pwm_pin: 21
  servo_dir_pin: 20
  servo_enc_a: 16
  servo_enc_b: 19
  zipper_enc_cs_pin: 2
  zipper_enc_clk_pin: 4
  zipper_enc_do_pin: 3
  limit_switch_pin: 15
  extension_per_step: 0.000004453125
  debounce_threshold_ms: 30

turret_encoder:
  cs_pin: 12
  clk_pin: 6
  do_pin: 13
  encoder_max_value: 1023
  offset: 0


turret_limit_switch:
  limit_switch_pin: 14
  debounce_threshold_ms: 30
  active_low: true

pitch_motor:
  motor_id: 10

yaw_motor:
  motor_id: 11


x_offset: 0.14
# y_offset is expressed as (y - h) 
y_offset: -0.185
pitch_kinematics_sign: -1.0
pitch_angle_offset_deg: 0.0

turret_id: 1
