spiral_zipper:
  servo_pwm_pin: 22
  servo_dir_pin: 27
  servo_enc_a: 24
  servo_enc_b: 25
  servo_enable_pin: 4
  zipper_enc_cs_pin: 13
  zipper_enc_clk_pin: 26
  zipper_enc_do_pin: 19
  limit_switch_pin: 16
  extension_per_step: 0.000004453125
  debounce_threshold_ms: 30

turret_encoder:
  cs_pin: 0
  clk_pin: 6
  do_pin: 5
  encoder_max_value: 1023
  offset: 0

turret_limit_switch:
  limit_switch_pin: 20
  debounce_threshold_ms: 30

pitch_motor:
  motor_id: 10

yaw_motor:
  motor_id: 11

socket: 0

x_offset: 0.0
y_offset: 0.0
