apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.05
    profile: false
    max_hamming: 0
    detector:
      threads: 2
      decimate: 1.0
      blur: 0.0
      refine: 1
      sharpening: 0.25
      debug: 0
    pose_estimation_method: pnp
    tag:
      ids: [0, 1]
      frames: [tag36h11_0, tag36h11_1]
      sizes: [0.05, 0.05]
