#ifndef LIMIT_SWITCH_H_
#define LIMIT_SWITCH_H_

#include <functional>
#include <unordered_map>
#include <chrono>
#include <cstdint>
#include <yaml-cpp/yaml.h>

/**
 * @brief Class to encapsulate a hardware limit switch using pigpio.
 */
class LimitSwitch {
 public:
  /// Callback type for state changes.
  using StateChangeCallback = std::function<void(bool)>;

  /**
   * @brief Constructs a LimitSwitch with a GPIO pin and debounce threshold.
   *        The constructor initializes the GPIO pin mode and registers
   *        the pigpio alert function.
   * @param gpio_pin The GPIO pin number.
   * @param debounce_threshold_ms Debounce threshold in milliseconds.
   */
  LimitSwitch(int gpio_pin, int debounce_threshold_ms = 30);

  /**
   * @brief Constructs a LimitSwitch using values from a YAML node.
   *        Expects keys "limit_switch_pin" and optionally "debounce_threshold_ms".
   * @param node YAML configuration node.
   */
  explicit LimitSwitch(const YAML::Node &node);

  ~LimitSwitch();

  /// Set the callback to be called on state changes.
  void SetStateChangeCallback(StateChangeCallback callback);

  /// Check whether the switch is currently pressed.
  bool IsPressed() const;

  /**
   * @brief Called when an alert is generated by pigpio.
   * @param level The GPIO level.
   * @param tick  The tick count.
   */
  void HandleAlert(int level, unsigned int tick);

  /**
   * @brief Global callback function that pigpio calls.
   *        It looks up the LimitSwitch instance by GPIO pin and calls HandleAlert.
   * @param gpio The GPIO pin number.
   * @param level The level of the pin.
   * @param tick  The tick count.
   */
  static void GlobalAlertCallback(int gpio, int level, unsigned int tick);

 private:
  int gpio_pin_;
  int debounce_threshold_ms_;
  bool last_state_;
  bool pressed_;
  StateChangeCallback callback_;
  std::chrono::steady_clock::time_point last_debounce_time_;

  // A static map to associate GPIO pins with LimitSwitch instances.
  static std::unordered_map<int, LimitSwitch*> instances_;
  //static LimitSwitch* instances_;
};

#endif  // LIMIT_SWITCH_H_
